# Main Portfolio Information
baseURL = "https://me.farog.click/"
languageCode = "en-us"
title = "Farog Basher"
theme = "PaperMod"

# Menu Configuration
[[menu.main]]
identifier = "home"
name = "Home ğŸ "
url = "/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects ğŸ‘¨ğŸ»â€ğŸ’»"
url = "/projects"
weight = 30

[[menu.main]]
identifier = "search"
name = "Search ğŸ”"
url = "/search"
weight = 50

[[menu.main]]
identifier = "Resume"
name = "Resume ğŸ¤"
url = "https://my-s3-pers-files.s3.us-east-2.amazonaws.com/Resume.pdf"
weight = 60

# Site Parameters
[params]
# Theme Settings
showToc = true
TocOpen = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideMeta = false

# SEO Settings
env = "production"

# Home Page Profile Mode
[params.profileMode]
enabled = true
title = "Farog Basher"
subtitle = "Hi ğŸ‘‹ I'm Farog, As a dedicated Networking and Systems Administrator, I excel at leveraging technology to solve complex problems. With over 2 years of hands-on experience as Networking and System Admin, I specialize in designing, implementing, and managing robust IT infrastructures, with a strong focus on networking, operating systems, and ensuring security and reliability."
imageUrl = "/home/me.jpg"
imageWidth = 220
imageHeight = 220

# List View Settings
hideDescriptionInList = false

# Cover Image Settings
[params.cover]
hiddenInList = false
hiddenInSingle = false

# Social Media Icons and Links
[[params.socialIcons]]
name = "email"
url = "mailto:faroog1995@hotmail.com"

[[params.socialIcons]]
name = "linkedin"
url = "http://www.linkedin.com/in/farogbasher"

[[params.socialIcons]]
name = "github"
url = "http://github.com/farogfayz"

# Search Configuration
[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

# Output Formats
[outputs]
home = ["HTML", "RSS", "JSON"]

# Markup Settings
[markup.goldmark.renderer]
unsafe = true